events {}

http {
  # =========================
  # Front (Next.js ServerSideRendering)
  # =========================
  upstream genie_front {
    server genie_front:3000;
  }

  # =========================
  # Back (Spring Boot API)
  # =========================
  upstream genie_back {
    server genie_back:8080;
  }

  server {
    listen 80;
    server_name genie.climbjava.com;
    # -------------------------
    # 프론트: 모든 페이지 요청
    # -------------------------
    location / {
      proxy_pass http://genie_front;

      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # -------------------------
    # 백엔드 API
    # -------------------------
    location /graphql {
      proxy_pass http://genie_back;

      # GraphQL은 대량의 데이터를 주고받을 수 있으므로 타임아웃을 넉넉히 설정
      proxy_connect_timeout 60s;
      proxy_send_timeout 60s;
      proxy_read_timeout 60s;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
    # 유일한 rest controller(graphql에서 첨부파일 처리하는 용도의 컨트롤러)
    location /graphql-upload {
      proxy_pass http://genie_back/graphql-upload;
    }
  }
}
